### ISSUE TITLE
RSS has stopped updating

### ISSUE THREAD

**Issue by CICISUN** [hexojs/hexo-generator-feed#10]
不知为何 我的plugin停止自动更新了 最后一次更新是在：1-14号
安装配置都没有问题 请问如何解决？

**Comment by tommy351** [comment]
請列出版本資訊和配置，我不會通靈啊大佬

**Comment by CICISUN** [comment]
hahahaha sorry...

hexo-generator-feed@0.2.1
hexo: 2.8.3

plugins:
- hexo-generator-feed

//_config.yml
feed:
  type: atom
  path: atom.xml
  limit: 100

Anything wrong here?

**Comment by kawaiiushio** [comment]
ERROR Plugin load failed: hexo-generator-feed
ReferenceError: hexo is not defined
    at Object.<anonymous> (/Users/ippotsuko/blog/node_modules/hexo-generator-feed/feed.js:4:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (/Users/ippotsuko/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/ippotsuko/blog/node_modules/hexo-generator-feed/index.js:6:30
    at /Users/ippotsuko/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/ippotsuko/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/ippotsuko/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/ippotsuko/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/ippotsuko/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/ippotsuko/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/Users/ippotsuko/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/Users/ippotsuko/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:419:13)


配置同上

**Comment by Xuanwo** [comment]
所以- -，新版还有问题么？

**Comment by akar1nchan** [comment]
新版沒問題了
