### ISSUE TITLE
TypeError: config.type.toLowerCase is not a function

### ISSUE THREAD

**Issue by yansheng836** [hexojs/hexo-generator-feed#134]
## 'Generate atom feed' will work:
```yml
feed:
  type: atom
  path: atom.xml
  limit: 100
```

## 'Generate both atom and rss2' feeds not work
```yml
feed:
  type: # Generate both atom and rss2 feeds
    - atom
    - rss2
  path:
    - atom.xml
    - rss2.xml
```

error info
```bash
$ hexo g
(node:9376) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
ERROR Plugin load failed: hexo-generator-feed
TypeError: config.type.toLowerCase is not a function
    at H:\Hexo\node_modules\hexo-generator-feed\index.js:16:26
    at fs.readFile.then.script (H:\Hexo\node_modules\hexo\lib\hexo\index.js:232:12)
    at tryCatcher (H:\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (H:\Hexo\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (H:\Hexo\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (H:\Hexo\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (H:\Hexo\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (H:\Hexo\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (H:\Hexo\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (H:\Hexo\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (H:\Hexo\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (H:\Hexo\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (H:\Hexo\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (H:\Hexo\node_modules\bluebird\js\release\promise.js:643:18)
    at H:\Hexo\node_modules\bluebird\js\release\nodeback.js:42:21
    at H:\Hexo\node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by SukkaW** [comment]
Please upgrade to latest hexo-generator-feed first.
