### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL: http://

### ISSUE THREAD

**Issue by 8zu** [hexojs/hexo-generator-feed#176]
I tried using the default setting in README.md

```
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:
```

But build got the following errors

```
TypeError [ERR_INVALID_URL]: Invalid URL: http://
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at new URL (internal/url.js:316:22)
    at cache.apply (/builds/8zu/logs/node_modules/hexo-generator-feed/node_modules/hexo-util/lib/url_for.js:34:18)
    at Cache.apply (/builds/8zu/logs/node_modules/hexo-generator-feed/node_modules/hexo-util/lib/cache.js:27:46)
    at Hexo.urlForHelper (/builds/8zu/logs/node_modules/hexo-generator-feed/node_modules/hexo-util/lib/url_for.js:30:16)
    at Hexo.autodiscoveryInject (/builds/8zu/logs/node_modules/hexo-generator-feed/lib/autodiscovery.js:14:64)
    at Hexo.tryCatcher (/builds/8zu/logs/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/builds/8zu/logs/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.each.filter (/builds/8zu/logs/node_modules/hexo/lib/extend/filter.js:60:50)
    at tryCatcher (/builds/8zu/logs/node_modules/bluebird/js/release/util.js:16:23)
...
```

`package.json`:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-markdown-it": "^4.1.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.2"
  }
}
```

If I disable autodiscovery (`autodiscovery: false`), then I got a similar error message
```
TypeError [ERR_INVALID_URL]: Invalid URL: http://
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at new URL (internal/url.js:316:22)
    at cache.apply (/builds/8zu/logs/node_modules/hexo-generator-feed/node_modules/hexo-util/lib/full_url_for.js:22:18)
    at Cache.apply (/builds/8zu/logs/node_modules/hexo-generator-feed/node_modules/hexo-util/lib/cache.js:27:46)
    at Hexo.fullUrlForHelper (/builds/8zu/logs/node_modules/hexo-generator-feed/node_modules/hexo-util/lib/full_url_for.js:18:16)
    at Hexo.module.exports (/builds/8zu/logs/node_modules/hexo-generator-feed/lib/generator.js:52:33)
```

Is the configuration wrong in some way?

**Comment by 8zu** [comment]
After bumping the underlying versions to

```
nodejs: v16.13.0
```
```
{
  "name": "hexo-site",
  "version": "0.0.1",
  "private": true,
  "hexo": {
    "version": "5.4.0"
  },
  "dependencies": {
    "hexo": "^5.4.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it": "^5.0.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-util": "^2.5.0"
  }
}
```

The situation is now solved!
